apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
{{- if .Values.storageClass.annotations }}
  annotations:
    {{- toYaml .Values.storageClass.annotations | nindent 4 }}
{{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
{{- if .Values.storageClass.type }}
parameters:
  type: {{ .Values.storageClass.type }}
{{- end }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- if .Values.storageClass.mountOptions }}
mountOptions:
  {{- toYaml .Values.storageClass.mountOptions | nindent 8 }}
{{- end }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion | default false }}
